version: "3.7"

services:

  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=db.local
      - VIRTUAL_PORT=8080

  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/certs:/etc/nginx/certs

  web:
    build: ./volumes/laravel8
    volumes:
      - ./apps/web:/var/www/html
      - ./volumes/laravel8/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./data/web/storage/app:/var/www/html/storage/app
      - ./data/web/storage/logs:/var/www/html/storage/logs
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=web.local
      - VIRTUAL_PORT=80