services:

  adminer:
    container_name: adminer
    image: adminer
    environment:
      - VIRTUAL_HOST=db.local
      - VIRTUAL_PORT=8080

  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/proxy/certs:/etc/nginx/certs

  web:
    container_name: web
    build: ./volumes/web
    volumes:
      - ./apps/web:/var/www/html
      - ./volumes/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./data/web/storage/app:/var/www/html/storage/app
      - ./data/web/storage/logs:/var/www/html/storage/logs
    depends_on:
      - database
    environment:
      - VIRTUAL_HOST=laravel.local
      - VIRTUAL_PORT=80